name: gestion_juegos
description: "Una aplicación para gestionar y ver detalles de videojuegos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.28
  path: ^1.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
