name: gestion_juegos
description: "Una aplicación para gestionar y ver detalles de videojuegos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
